### ISSUE TITLE
typing.py  issubclass()

### ISSUE THREAD

**Issue by owlman2222** [alexshpilkin/dvrip#2]
Hi alex

I have installed your dvrip via pip but i am struggling to run your code pass this error

   File "C:\Python36\lib\site-packages\dvrip\typing.py", line 80, in json_to
    return type.json_to  # type: ignore
AttributeError: 'tuple' object has no attribute 'json_to'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dvrip_test.py", line 8, in <module>
    from dvrip.io import DVRIPClient
  File "C:\Python36\lib\site-packages\dvrip\io.py", line 8, in <module>
    from .info import GetInfo, Info
  File "C:\Python36\lib\site-packages\dvrip\info.py", line 72, in <module>
    class DiskInfo(Object):
  File "C:\Python36\lib\site-packages\dvrip\typing.py", line 360, in __new__
    member.__set_name__(self, mname)
  File "C:\Python36\lib\site-packages\dvrip\typing.py", line 301, in __set_name__
    self.pipe = (jsontype(get_args(ann)[0]),)
  File "C:\Python36\lib\site-packages\dvrip\typing.py", line 138, in jsontype
    return (json_to(type), for_json)
  File "C:\Python36\lib\site-packages\dvrip\typing.py", line 87, in json_to
    if issubclass(type, bool):  # needs to come before 'int'
TypeError: issubclass() arg 1 must be a class

when you print whats happening it getting stuck on

(typing.List, <class 'dvrip.info.PartitionInfo'>)

i am using python 3.6.7 on windows

many thanks
jon

**Comment by owlman2222** [comment]
Sorted it did a fresh install of python 3.7.4 
many thanks

**Comment by alexshpilkin** [comment]
Yeah, for some reason setup.py doesn’t complain when Python is too old even though I have set `python_requires='>= 3.7'`. Closing this for now, but suggestions are welcome if you have any.

**Comment by alexshpilkin** [comment]
@owlman2222 Do you still have your old 3.6.7 installation? Can you please check which pip version it came with?

**Comment by owlman2222** [comment]
pip version on 3.6.7 is 19.2.2,
Quick fix might be to put it in bold in the readme.rst

**Comment by pfalcon** [comment]
> `python_requires='>= 3.7`. Closing this for now, but suggestions are welcome if you have any.

May I chime in? My humble suggestion is to not target obscure novelties like cpython3.7, as that limits the userbase and leads to confusion.

**Comment by alexshpilkin** [comment]
I finally understand why `python_requires` was getting ignored! A newline was accidentally included in the package summary, and this led to an invalid PKG-INFO due to pypa/setuptools#1390. Fixed in e76df1d.

This project is currently undergoing a rewrite, and this bug should be fixed once it is complete, but tell me if you bump into this and I’ll cut a release using the current source.

**Comment by alexshpilkin** [comment]
@pfalcon I’d expect being in Debian stable would put Python 3.7 under the “pretty widespread” category, but I’ve no idea how common it actually is. Matters of opinion aside, I use [typing_inspect][1] to inspect type annotations in [dvrip.typing][2], and it officially supports Python ≥3.7 only, so that’s what I required. I’ve looked at the source, though, and it seems like the code to support 3.6 is still present, so if pressed I could probably relax the requirement to ≥3.6.

Relaxing it further would mean giving up on [PEP 526][3] variable annotations. I’m unwilling to do that, because it would make the code significantly uglier.

[1]: https://github.com/ilevkivskyi/typing_inspect
[2]: https://github.com/alexshpilkin/dvrip/blob/e76df1d091d85aa6cffb5c332ba6ae419ac9ac89/dvrip/typing.py
[3]: https://www.python.org/dev/peps/pep-0526/
